FROM ubuntu:18.04

RUN apt-get update 


RUN apt-get install -y openjdk-8-jdk openssh-server && \
update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java


ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
ENV PATH=${JAVA_HOME}/bin:${PATH}


RUN groupadd -g 1000 superman && \
useradd -u 1000 -g superman -s /bin/bash -m -d /home/superman superman &&  usermod -aG sudo superman










RUN apt-get update && \
    apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg \
    lsb-release \
    software-properties-common

# Add Docker's official GPG key
RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

# Set up the Docker repository
RUN add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

# Install Docker CE
RUN apt-get update && \
    apt-get install -y docker-ce docker-ce-cli containerd.io










RUN echo 'superman:abc123' | chpasswd

RUN service ssh start

EXPOSE  22
VOLUME /var/run/docker.sock

CMD tail -f /dev/null