version: '3'
services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    privileged: true
    user: root
    ports:
      - 8770:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - /home/ubuntu/jenkins_compose/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock